### ISSUE TITLE
I got banned today

### ISSUE THREAD

**Issue by NewthanGuy** [NewthanGuy/CMDV4#18]
I got banned from cvm today next day i Will Get banned windfuf

This isnt a issue Windfuf But Just warning you

This Fake issue Will be closed when Good_night_forever/kabecinha11 gets Unbanned

Hildaboo Banned me for No reason

**Comment by Zinffo** [comment]
thats weird, you can use a VPN though

**Comment by Zinffo** [comment]
use windscribe, they are free vpn

**Comment by Zinffo** [comment]
> But what free one to use that Works i cant pay for vpns

also i think we can make CMDV5 now, we are on cmdv4 for so long

**Comment by NewthanGuy** [comment]
Okay i made CmdV5 tho now i need you to Code it

**Comment by NewthanGuy** [comment]
Also thanks for the vpn

**Comment by NewthanGuy** [comment]
The vpn didnt work with cvm tho
